### ISSUE TITLE
Request for Contribution 🤕🗣🆘

### ISSUE THREAD

**Issue by alphaolomi** [alphaolomi/food-server#1]
Looking for contributor if you think you can help in any way kindly help out in the project.

**Comment by alphaolomi** [comment]
Looking forward on @gordonnchy
Looking forward on @mwalongoFrancis

**Comment by gordonnchy** [comment]
we gonna work this out

**Comment by mwalongoFrancis** [comment]
noted with thanks!! bless boss

**Comment by gordonnchy** [comment]
what can we work on this? @alphaolomi

**Comment by gordonnchy** [comment]
Did you remove the app from heroku? @alphaolomi

**Comment by alphaolomi** [comment]
Hello @gordonnchy 

After several design and engineering decision i finally settled the current tech stack

Few months i started it all together development going slow but this time done right

1. yes we can work on this , if your up then i can add more attention to it
2. after few months with little dev i removed the heroku instance, but i can out it back online together with some CI/CD pipelines

**Comment by gordonnchy** [comment]
i got time for couple coming weeks so you can share some ideas @alphaolomi

**Comment by alphaolomi** [comment]
Sure thing
